name: Erin Canning
favicon: null
layout_spectrum: 0.48621
typography_spectrum: 0.55811
title: Erin Canning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffcc5'
    - '#7c94ac'
    - '#070508'
    - '#b8d6d8'
    - '#393e5e'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
