name: eecanning
favicon: null
layout_spectrum: 0.15201207995414734
typography_spectrum: 0.8597247402649373
title: Erin Canning
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6256255633197725
  lightness: 0.9911586097441614
  saturation: 0.6048561923671514
  rhythmicContrast: 0.5944893464911729
purpose: []
